GET http://localhost:4000/users

###

GET http://localhost:4000/maps/6

###

GET http://localhost:4000/notes/folder/9

###

POST http://localhost:4000/users
Content-Type: application/json

{
  "email": "paula@email.com",
  "password": "hejsan"
}

###

POST http://localhost:4000/users/login
Content-Type: application/json

{
  "email": "paula@email.com",
  "password": "hejsan"
}
###

POST http://localhost:4000/maps/user=12
Content-Type: application/json

{
  "title": "Paulas mapp!"
}

###

POST http://localhost:4000/notes/map=7
Content-Type: application/json

{
  "title": "Paulas första inlägg",
  "text": "Hejsan svejsan i skogen!"
}


###

PUT http://localhost:4000/maps/2
Content-Type: application/json

{
  "title": "My First Map"
}

###

PUT http://localhost:4000/notes/change/7
Content-Type: application/json

{
  "title": "Third title that",
  "text": "will be MOOOOOVED"
}

###

PUT http://localhost:4000/notes/switchMap/7
Content-Type: application/json

{
  "mapId": 3
}

###


DELETE http://localhost:4000/maps/delete/5
Content-Type: application/json

###

DELETE http://localhost:4000/notes/delete/4
Content-Type: application/json
