GET http://localhost:4000/users

###

GET http://localhost:4000/maps/6

###

GET http://localhost:4000/notes/1

###

POST http://localhost:4000/users
Content-Type: application/json

{
  "email": "user_3@email.com",
  "password": "TestTestTest"
}

###

POST http://localhost:4000/users/login
Content-Type: application/json

{
  "email": "user_1@email.com",
  "password": "TestTest"
}
###

POST http://localhost:4000/maps/user=11
Content-Type: application/json

{
  "title": "First map for user_3"
}

###

POST http://localhost:4000/notes
Content-Type: application/json


###

PUT http://localhost:4000/maps/2
Content-Type: application/json

{
  "title": "My First Map"
}

###

PUT http://localhost:4000/notes/:id
Content-Type: application/json

###

DELETE http://localhost:4000/maps/delete/5
Content-Type: application/json

###

DELETE http://localhost:4000/notes/:id
Content-Type: application/json
